### ISSUE TITLE
Migrate storage and workflows to Oregon

### ISSUE THREAD

**Issue by brews** [ClimateImpactLab/downscaleCMIP6#640]
As R&D spins down on this project, we will try to move all the storage for this project over to the west coast (us-west1 on GCP). One of the main reasons is that this co-located the stored data with the majority of our computers.

We originally separated our compute and storage across the US west coast, the US Midwest, and Europe so that critical projects wouldn't fight each other for resource quotas. This is no longer an issue.

As part of transition, I think we would sunset and tear down the custom cluster in the midwest (defined in /infrastructure/terraform) and instead have future work run in a new namespace on workflows.cilresearch.org. This reduces the weight of maintenance.

- [x] make sibling buckets in new region (#638)
- [x] move wanted data into new buckets
- [x] fix hard-coded URLs in workflows (#639)
- [x] migrate argo workflow stuff to workflows.cilresearch.org in new downscalecmip6 namespace (https://github.com/ClimateImpactLab/cilresearch-infra/pull/16, https://github.com/ClimateImpactLab/cilresearch-infra/pull/17, https://github.com/ClimateImpactLab/cilresearch-deployments/commit/8a7767323619f431c39e2e544a76fc06eaafbab9, https://github.com/ClimateImpactLab/cilresearch-deployments/commit/3b2ab5b63e84897b51cfc91ce45717cbcef2f2d8)
- [x] do sanity check/test run of argo downscalecmip6 workflow (confirm we can run workflow, major required data is in the right place.)
- [x] delete old data and buckets in Iowa (#643)
- [x] tear down k8s cluster in Iowa - future runs on workflows.cilresearch.org (#643)

**Comment by brews** [comment]
Okay, got new nodes up on cilresearch.org and migrated the downscaling workflows templates into the default namespace. They appear to run in the new cluster/region. 👍 

I would like to get the permissions and templates set up so they can run in their own "downscalingcmip6" namespace without cluttering the default one. That isn't as pressing as just ensuring they run.

**Comment by brews** [comment]
Alright, and with this, we don't have need for a fancy, project-specific infrastructure setup, so I also removed the infrastructure/ directory in #643.

Closing.
